Shoppee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls',namespace='users')),
    path('orders/', include('apps.orders.urls',namespace='orders')),
    path('shop/', include('apps.shop.urls',namespace='shop')),
    path('cart/', include('apps.cart.urls',namespace='cart')),
    path('logs/', include('apps.logs.urls',namespace='logs')),
    path('login', views.LoginView.as_view(),name='login'),
    path('', views.home.as_view(),name='home'),
    path('profile', views.Profile.as_view(),name='profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orders/urls.py
from django.urls import path 
from . import views
app_name = 'apps.orders'

urlpatterns = [
    path('add-order/', views.ajax_create_order, name='add_order'),
    path('get-orders/', views.ajax_get_orders, name='get_orders'),
    path('get-order/<str:pk>/', views.ajax_get_order, name='get_order'),
    path('accept-orders/', views.ajax_accept_order, name='accepts_orders'),
    # path('items/', views.ajax_my_cart, name='my_cart_items'),
]

apps/shop/urls.py
from django.urls import path 
from . import views

app_name = 'apps.shop'

urlpatterns = [
    path('ajax-ads/', views.ajax_get_ads, name='ads'),
    path('ajax-items/', views.ajax_get_items, name='items'),
    path('ajax-item-edit/', views.ajax_get_edit_item, name='edit_item'),
    path('ajax-item-ads/', views.ajax_get_edit_ad, name='edit_ads'),
    path('ajax-item-update/', views.ajax_update_item, name='update_item'),
    path('ajax-item-delete/', views.ajax_delete_item, name='delete_item'),
    path('ajax-ad-delete/', views.ajax_delete_ad, name='delete_ad'),
    path('ajax-ad-update/', views.ajax_update_ad, name='update_ad'),
    path('ajax-items-owner/', views.ajax_get_items_owner, name='items_owner'),
    path('ajax-ads-owner/', views.ajax_get_items_owner, name='ads_owner'),
    path('ajax-create-ads/', views.ajax_craete_ads, name='create_ads'),
    path('ajax-create-item/', views.ajax_craete_item, name='create_item'),
    path('ajax-add-item-stock/', views.ajax_add_item_stock, name='add_item_stock'),
    path('items/', views.ItemsView.as_view(), name='items_view'),
    path('edit-items/', views.ajax_item_edit, name='edit_items'),
    path('edit-ads/', views.ajax_ads_edit, name='ads_items'),
    path('item/', views.ajax_get_item, name='item'),
]

apps/orders/models.py
from django.db import models
from Shoppee.models import BaseModel
from apps.users.models import MyCustomUser
from apps.shop.models import Item
from .helpers import *
# Create your models here.




class Order(BaseModel):
    owner = models.ForeignKey(
        MyCustomUser,
        related_name='orders',
        on_delete=models.CASCADE,

    )
    order_number = models.CharField(
        unique=True,
        max_length=100,
        blank=False,
    )
    status = models.CharField(
        max_length=20,
        blank=False,
        choices=STATUS_CHOICES,
        default='pending',
    )

    def __str__(self):
        return self.order_number
    
    @property
    def get_total(self):
        total = 0
        for item in self.order_item.all():
            total+=item.total
        return total
    @property
    def can_approve(self):
        for item in self.order_item.all():
            if item.quantity > item.item.stock:
                return False
        return True

    @property
    def get_shop(self):
        for item in self.order_item.all():
            shop = item.item.shop
        return shop

class OrderItem(BaseModel):
    order = models.ForeignKey(
        Order,
        related_name='order_item',
        on_delete=models.CASCADE
    )
    item = models.ForeignKey(
        Item,
        related_name='ordered_item',
        on_delete=models.CASCADE,
    )
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.item.name}"

    @property
    def total(self):
        return self.quantity*self.item.price
    @property
    def get_shop(self):
        return self.item.shop

apps/orders/views.py
from django.shortcuts import render
import random
import string


# Create your views here.


from django.urls import reverse_lazy
from django.http import (HttpResponseRedirect, JsonResponse)
from django.views.generic.base import TemplateView

from apps.users.models import MyCustomUser
from apps.shop.models import Item
from apps.cart.models import *
from .models import *
from django.template.loader import render_to_string
from apps.shop.models import *
from django.db.models import Q
from apps.logs import views as logs



def ajax_create_order(request):


    items = request.POST.getlist('items')
    quantities = request.POST.getlist('quantities')
    order_number = get_random_string(20)
    Order.objects.create(owner = request.user,
        order_number = order_number,
        status='pending'
    )
    target = None
    order = Order.objects.get(order_number = order_number)
    for i in range(0, len(items)):
        my_item = Item.objects.get(id = items[i])
        add_item_order(my_item,order,quantities[i])
        remove_cart_item(my_item,request.user)
        target = my_item.shop.user
    logs.send_notification(request.user,order, 'Placed an Order',target, 'important','')
    return JsonResponse({
        'success':True,
    })

def add_item_order(item,order,quantity):
    OrderItem.objects.create(
        order= order,
        item=item,
        quantity=quantity,
    )

def remove_cart_item(item, user):
    cart = Cart.objects.get(owner = user)
    my_item = CartItem.objects.get(
        cart=cart,
        item = item,
    )
    my_item.delete()


def get_random_string(length):

    import datetime 

    dt = datetime.datetime.now()
    seq = int(dt.strftime("%Y%m%d%H%M%S"))
    chars = string.ascii_lowercase
    result_str = ''.join(random.choice(chars) for i in range(length))
    return str(seq)+result_str

def ajax_get_orders(request):
    status = request.GET.get('status')
    order = Order.objects.filter(status = status)
    if status == 'preparing':
        order = Order.objects.filter( Q(status = status) | Q(status = 'request_cancel'))

    items = Item.objects.all()
    htmlStr = render_to_string('render_orders.html', {
        'orders':order,
        'items':items,
        'status':status,
    })

    if request.user.user_type == 'shopper':
        order = Order.objects.filter( owner = request.user, status = status)
        if status == 'preparing':
            order = Order.objects.filter(Q( owner = request.user) &(Q(status = status)|Q(status = 'request_cancel')))
        htmlStr = render_to_string('render_orders_shopper.html', {
        'orders':order,
        'status':status,
        })

    
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
    })

def ajax_accept_order(request):
    status = request.POST.get('status')
    order = Order.objects.get(order_number = request.POST.get('order_number'))
    current_status = order.status
    if status == 'request_cancel' and current_status == 'otw':
        return JsonResponse({
        'success': True,
        'message':'Operation failed the order already out for delivery.',
        })
    if status == 'canceled' and current_status == 'preparing':
        order.status = 'request_cancel'
        order.save()
        
        shop = order.get_shop
        owner = shop.user
        
        logs.send_notification(request.user,order,'is requesting to cancel order:',owner,'important','')
        return JsonResponse({
        'success': True,
        'message':'Operation failed your order has already been approved. We notified the seller that you want to cancel your order.',
        })
    if current_status == 'canceled':
        return JsonResponse({
        'success': True,
        'message':'Operation failed the order was canceled by the customer.',
        })
        
    order.status = status
    order.save()
    shop = order.get_shop
    owner = shop.user
    message = 'Operation was successful'

    items = OrderItem.objects.filter(order = order)
    
    if current_status == 'request_cancel' and status == 'canceled':
        for item in items:
            update_item_stock(item.quantity*(-1),item.item.id)
            #notify user
        logs.send_notification(request.user,order,'Approved cancelation of Order:',order.owner,'important','')
        message = 'Operation was successful. Order was canceled. All Items has been restored.'
    if status == 'preparing':
        for item in items:
            update_item_stock(item.quantity,item.item.id)
            #notify user
        logs.send_notification(request.user,order,'Approved your order :',order.owner,'important','')
        message = 'Order Accepted.'
    if status == 'canceled' and current_status == 'pending':
        message = 'Your order has been canceled.'
    if status == 'otw':
        #notify user
        logs.send_notification(request.user,order,'Seller has sent your your order and is now Out for Delivery :',order.owner,'important','')
        message = 'Order is now out for delivery.'
    if status == 'recieved':
        #notify seller
        logs.send_notification(request.user,order,'Customer Recived his/her Order :',owner,'important','')
        message = 'Order has been recieved.'
    if status == 'request_cancel':
        #notify seller
        logs.send_notification(request.user,order,'is requesting to cancel order:',owner,'important','')
        message = 'Request to cancel order has been sent to seller.'

    
    return JsonResponse({
        'success': True,
        'message': message,
    })

def update_item_stock(quantity, item_id):
    item = Item.objects.get(id = item_id)
    stock =  item.stock
    item.stock = (stock - (quantity))
    item.save()

def ajax_get_order(request, pk):
    logs.mark_as_read(request.GET.get('id'))
    if request.user.user_type == 'shopper':
        order = Order.objects.get(order_number = pk)
        htmlStr = render_to_string('render_order.html', {
            'order':order,
        })
        return JsonResponse({
            'success': True,
            'htmlStr': htmlStr,
        })
    else:
        order = Order.objects.get(order_number = pk)
        htmlStr = render_to_string('render_order_seller.html', {
            'order':order,
        })
        return JsonResponse({
            'success': True,
            'htmlStr': htmlStr,
        })

apps/orders/templates/render_items_order.html
<div style="position: sticky; top: 0px; background-color: cornflowerblue; padding: 5px;">
    <div style="display: flex; padding: 5px;">
        <div style="width: 60%;">Item Name </div>
        <div style="width: 20%;">Stock </div>
        <div>Ordered </div>
    </div>
</div>
{% for item in items.all %}

{% if item.stock == 0 %}
<div style="display: flex; background-color: red; padding: 5px; margin-top: 5px; margin-right: 5px; padding-left: 10px;">
    <div style="width: 60%;">{{ item.name}} </div>
    <div style="width: 20%;">{{ item.stock}} </div>
    <div>{{ item.get_total_ordered}} </div>
</div>
{% elif item.get_total_ordered > item.stock %}

<div style="display: flex; background-color: orange; padding: 5px; margin-top: 5px; margin-right: 5px; padding-left: 10px;">
    <div style="width: 60%;">{{ item.name}} </div>
    <div style="width: 20%;">{{ item.stock}} </div>
    <div>{{ item.get_total_ordered}} </div>
</div>
{% else %}
<div style="display: flex;padding: 5px;   margin-top: 5px; margin-right: 5px; padding-left: 10px;">
    <div style="width: 60%;">{{ item.name}} </div>
    <div style="width: 20%;">{{ item.stock}} </div>
    <div>{{ item.get_total_ordered}} </div>
</div>
{% endif %}
{% endfor %}

apps/orders/templates/render_order.html
{% autoescape off %}
{% load static %}
{% if order %}
<div style="margin: 20px; border: solid 1px black; padding: 10px; background-color: darkslategray; top: 6vh; position: relative;" data-ajax-url="{% url 'orders:accepts_orders' %}" 
id="orderUrl">
    <span style="margin: 10px; font-size: 16px; display: block;;">Order Number : {{ order.order_number }}</span>
    <span style="margin: 10px; font-size: 16px; display: block;;">Delivery Address : Customer Address</span>
    <span style="margin: 10px; font-size: 16px; display: block;;">Ordered : {{ order.created_at | timesince }} ago</span>
    {% if order.status == 'canceled' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date Canceled: {{ order.modified_at }}</span>
    {% elif order.status == 'preparing' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date Approved: {{ order.modified_at }}</span>
    {% elif order.status == 'request_cancel' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date of Request: {{ order.modified_at }}</span>
    {% elif order.status == 'otw' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date of Delivery: {{ order.modified_at }}</span>
    {% elif order.status == 'recieved' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date Delivered: {{ order.modified_at }}</span>
    {% else %}
    {% endif %}
    <div style="border: solid 1px black; padding: 10px;" >
        <div style="display: flex;">
            <span style="width: 100px;">Quantity</span> <span>Items</span>
        </div>
        <hr>
        {% for item in order.order_item.all %}
        
        <div style="display: flex; margin-top: 5px; background-color: lightgreen; padding: 3px;">
            <span style="width: 100px;">{{ item.quantity }} pc/s</span> 
            <span style="width: -webkit-fill-available;">{{ item.item.name }}</span>
            <span style="width: 20%; text-align: right;">{{ item.total }}</span>
        </div>
        {% endfor %}
    </div>
    <div style="width: 100%;">
        <span style="float: right; padding: 10px;">Grand Total : {{ order.get_total }}</span>

    </div>
    <div style="display: flex; width: 100%; justify-content: center;">
        {% if order.status == 'recieved' %}
        <button style="width: 50%; padding: 10px;  margin: auto;" >Rate Items</button>
        {% elif order.status == 'canceled' %}
        {% elif order.status == 'pending' %}
        <button style="width: 50%; padding: 10px;  margin: auto;" onclick="approve('{{ order.order_number }}','canceled')" >Cancel Order</button>
        {% elif order.status == 'otw' %}
        <button style="width: 50%; padding: 10px;  margin: auto;"  onclick="approve('{{ order.order_number }}','recieved')" >Recieved Order</button>
        {% else %}
        {% if order.status == 'request_cancel' %}
        <span>Request to Cancel order has been sent</span>
        {% else %}
        <button style="width: 50%; padding: 10px;  margin: auto;" onclick="approve('{{ order.order_number }}','request_cancel')">Request to Cancel Order</button>
        {% endif %}
        {% endif %}
    </div>
</div>
{% else %}
<div style="text-align: center; padding-top: 40vh; ">There was an error.</div>
{% endif %}


{% block js %}
<script src="{% static 'js/orders.js' %}"></script>

{% endblock %}

{% endautoescape %}

apps/orders/templates/render_order_seller.html
{% autoescape off %}
{% load static %}
{% if order %}
<div style="margin: 20px; border: solid 1px black; padding: 10px; background-color: darkslategray; top: 6vh; position: relative;" data-ajax-url="{% url 'orders:accepts_orders' %}" data-ajax-id="{{ order.id }}"
id="orderUrl">
    <span style="margin: 10px; font-size: 16px; display: block;;">Order Number : {{ order.order_number }}</span>
    <span style="margin: 10px; font-size: 16px; display: block;;">Customer : {{ order.owner.full_name }}</span>
    <span style="margin: 10px; font-size: 16px; display: block;;">Delivery Address : Customer Address</span>
    <span style="margin: 10px; font-size: 16px; display: block;;">Ordered : {{ order.created_at | timesince }} ago</span>
    {% if order.status == 'canceled' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date Canceled: {{ order.modified_at }}</span>
    {% elif order.status == 'preparing' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date Approved: {{ order.modified_at }}</span>
    {% elif order.status == 'request_cancel' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date of Request: {{ order.modified_at }}</span>
    {% elif order.status == 'otw' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date of Delivery: {{ order.modified_at }}</span>
    {% elif order.status == 'recieved' %}
    <span style="margin: 10px; font-size: 16px; display: block;;">Date Delivered: {{ order.modified_at }}</span>
    {% else %}
    {% endif %}
    <div style="border: solid 1px black; padding: 10px;" >
        <div style="display: flex;">
            <span style="width: 100px;">Quantity</span> <span>Items</span>
        </div>
        <hr>
        {% for item in order.order_item.all %}
        
        {% if not order.status == 'pending' %}

        <div style="display: flex; margin-top: 5px; background-color: lightgreen; padding: 3px;">
            <span style="width: 100px;">{{ item.quantity }} pc/s</span>
            <span style="width: -webkit-fill-available;">{{ item.item.name }}</span>
            <span style="width: 20%; text-align: right;">{{ item.total }}</span>
        </div>
        {% elif item.item.stock == 0 or item.quantity > item.item.stock %}
        <div style="display: flex; margin-top: 5px; background-color: red; padding: 3px;">
            <span style="width: 100px;">{{ item.quantity }} pc/s</span>
            <div class="tooltip" style="width: -webkit-fill-available;">{{ item.item.name }}
                <span class="tooltiptext">Not enough stock in inventory</span>
            </div>
            <span style="width: 20%; text-align: right;">{{ item.total }}</span>
        </div>
        {% elif item.item.get_total_ordered > item.item.stock %}
        <div style="display: flex; margin-top: 5px; background-color: orange; padding: 3px;">
            <span style="width: 100px;">{{ item.quantity }} pc/s</span>
            <div class="tooltip" style="width: -webkit-fill-available;">{{ item.item.name }}
                <span class="tooltiptext">This Item Has more order than your current stock</span>
            </div>
            <span style="width: 20%; text-align: right;">{{ item.total }}</span>
        </div>
        {% else %}
        <div style="display: flex; margin-top: 5px; background-color: lightgreen; padding: 3px;">
            <span style="width: 100px;">{{ item.quantity }} pc/s</span>
            <span style="width: -webkit-fill-available;">{{ item.item.name }}</span>
            <span style="width: 20%; text-align: right;">{{ item.total }}</span>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div style="width: 100%;">
        <span style="float: right; padding: 10px;">Grand Total : {{ order.get_total }}</span>

    </div>
    <div style="display: flex; width: 100%; justify-content: center;">
        {% if order.status == 'pending' %}
        {% if not order.can_approve %}
        <button style="width: 50%; padding: 10px;" disabled>Approve</button>
        {% else %}
        <button style="width: 50%; padding: 10px;"
            onclick="approve('{{ order.order_number }}','preparing')">Approve</button>
        {% endif %}
        <button style="width: 50%; padding: 10px;">Void Order</button>
        {% elif order.status == 'preparing' %}
        {% if order.status == 'request_cancel' %}
        <button style="width: 50%; padding: 10px; margin: auto;"
            onclick="approve('{{ order.order_number }}','canceled')">Approve Cancelation</button>
        {% endif %}
        <button style="width: 50%; padding: 10px; margin: auto;"
            onclick="approve('{{ order.order_number }}','otw')">Deliver</button>
        {% elif order.status == 'otw' %}
        {% else %}
        {% endif %}
    </div>
</div>
{% else %}
<div style="text-align: center; padding-top: 40vh; ">There was an error.</div>
{% endif %}


{% block js %}
<script src="{% static 'js/orders.js' %}"></script>

{% endblock %}

{% endautoescape %}

apps/orders/templates/render_orders.html
{% autoescape off %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static 'css/items.css' %}" type="text/css">
{% endblock %}


<div style="position: absolute; top: 6vh; width: 100%; height: -webkit-fill-available;background-color: antiquewhite; padding: 20px; display: flex; margin: auto;">
    <div class="rightDiv"
        style="height: 100%;width: 30%; background-color: cadetblue; margin: auto; margin-right: 10px; padding: 10px;">
        <div>

            <h2 style="text-align: center; padding: 20px;">Items Inventory Summary</h2>
        </div>
        <div style="width: auto; height: 83%;  overflow-y: scroll; ">

            {% include 'render_items_order.html' %}
        </div>
        <div class="title" style="height: 70px; width: 100%; position: sticky; bottom: 0px;">
            <div>Legend</div>
            <div style="text-align: center; width: 100%; display: flex;">
                <div style="width: 20px; height: 20px; background-color: lightgreen;margin-left: 10px;"></div><span
                    style="font-size: 12px; width: 30%; text-align: left; padding: 3px;">All Good</span>
                <div style="width: 20px; height: 20px; background-color: orange;"></div><span
                    style="font-size: 12px; width: 30%; text-align: left;padding: 3px;">There are more order than your
                    current stock</span>
                <div style="width: 20px; height: 20px; background-color: red;"></div><span
                    style="font-size: 12px; width: 30%; text-align: left;padding: 3px;">Out of Stock</span>

            </div>
        </div>
    </div>
    <div class="leftDiv"
        style="height: 100%;width: 70%; overflow-y: scroll; background-color: rgb(161, 148, 148); margin-left: 10px; margin: auto;">
        <div class="title" style="height: auto; width: 100%; text-align: left;" data-ajax-url="{% url 'orders:accepts_orders' %}"
            id="orderUrl">
            <form>
                <input type="text" name="search" placeholder="Search Orders.." class="searchItems"
                    style="float: right; top: 0px;">
            </form>
            <span style="padding: 10px;">Status</span>
            <select name="" id="xx" style="padding: 5px; margin: 3px;" onchange="viewOrders(this.options[this.selectedIndex].value)">
                <option value="pending">Pending</option>
                <option value="preparing">Preparing</option>
                <option value="otw">Out For Delivery</option>
                <option value="recieved">Delivered</option>
                <option value="canceled">Canceled</option>
            </select>
            <span style="padding: 10px;">Month</span>
            <select name="" id="xxx" style="padding: 5px; margin: 3px;">
                <option value="pending">All</option>
                <option value="pending">January</option>
                <option value="preparing">February</option>
                <option value="otw">March</option>
                <option value="recieved">April</option>
                <option value="canceled">May</option>
                <option value="canceled">June</option>
                <option value="canceled">July</option>
                <option value="canceled">August</option>
                <option value="canceled">September</option>
                <option value="canceled">October</option>
                <option value="canceled">November</option>
                <option value="canceled">December</option>
            </select>
            <span style="padding: 10px;">Year</span>
            <select name="" id="xxxx" style="padding: 5px; margin: 3px;" >
                <option value="pending">All</option>
                <option value="pending">2023</option>
                <option value="preparing">2024</option>
                <option value="otw">2025</option>
                <option value="recieved">2026</option>
                <option value="canceled">2027</option>
            </select>
        </div>
        <div class="itemsContainer" id="itemsContainer" data-ajax-url-edit="{% url 'shop:edit_ads' %}">

            {% include 'render_orders_item.html' %}
        </div>


    </div>


    {% block js %}
    <script src="{% static 'js/orders.js' %}"></script>

    {% endblock %}




    {% endautoescape %}

apps/orders/templates/render_orders_shopper.html
{% autoescape off %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static 'css/items.css' %}" type="text/css">
{% endblock %}


<div style="position: absolute; top: 6vh; width: 100%; height: -webkit-fill-available;background-color: antiquewhite; padding: 20px; display: flex; margin: auto;">
    {% if user.user_type == 'seller' %}
    <div class="rightDiv"
        style="height: 100%;width: 30%; background-color: cadetblue; margin: auto; margin-right: 10px; padding: 10px;">
        <div>

            <h2 style="text-align: center; padding: 20px;">Items Inventory Summary</h2>
        </div>
        <div style="width: auto; height: 83%;  overflow-y: scroll; ">

            {% include 'render_items_order.html' %}
        </div>
        <div class="title" style="height: 70px; width: 100%; position: sticky; bottom: 0px;">
            <div>Legend</div>
            <div style="text-align: center; width: 100%; display: flex;">
                <div style="width: 20px; height: 20px; background-color: lightgreen;margin-left: 10px;"></div><span
                    style="font-size: 12px; width: 30%; text-align: left; padding: 3px;">All Good</span>
                <div style="width: 20px; height: 20px; background-color: orange;"></div><span
                    style="font-size: 12px; width: 30%; text-align: left;padding: 3px;">There are more order than your
                    current stock</span>
                <div style="width: 20px; height: 20px; background-color: red;"></div><span
                    style="font-size: 12px; width: 30%; text-align: left;padding: 3px;">Out of Stock</span>

            </div>
        </div>
    </div>
    {% endif %}
    <div class="leftDiv"
        style="height: 100%;width: 70%; overflow-y: scroll; background-color: rgb(161, 148, 148); margin-left: 10px; margin: auto;">
        <div class="title" style="height: auto; width: 100%; text-align: left;" data-ajax-url="{% url 'orders:accepts_orders' %}"
            id="orderUrl">
            <form>
                <input type="text" name="search" placeholder="Search Orders.." class="searchItems"
                    style="float: right; top: 0px;">
            </form>
            <span style="padding: 10px;">Status</span>
            <select name="" id="xx" style="padding: 5px; margin: 3px;" onchange="viewOrders(this.options[this.selectedIndex].value)">
                <option value="pending">Pending</option>
                <option value="preparing">Preparing</option>
                <option value="otw">Out For Delivery</option>
                <option value="recieved">Recieved Orders</option>
                <option value="canceled">Canceled</option>
            </select>
            <span style="padding: 10px;">Month</span>
            <select name="" id="xxx" style="padding: 5px; margin: 3px;">
                <option value="pending">All</option>
                <option value="pending">January</option>
                <option value="preparing">February</option>
                <option value="otw">March</option>
                <option value="recieved">April</option>
                <option value="canceled">May</option>
                <option value="canceled">June</option>
                <option value="canceled">July</option>
                <option value="canceled">August</option>
                <option value="canceled">September</option>
                <option value="canceled">October</option>
                <option value="canceled">November</option>
                <option value="canceled">December</option>
            </select>
            <span style="padding: 10px;">Year</span>
            <select name="" id="xxxx" style="padding: 5px; margin: 3px;" >
                <option value="pending">All</option>
                <option value="pending">2023</option>
                <option value="preparing">2024</option>
                <option value="otw">2025</option>
                <option value="recieved">2026</option>
                <option value="canceled">2027</option>
            </select>
        </div>
        <div class="itemsContainer" id="itemsContainer" data-ajax-url-edit="{% url 'shop:edit_ads' %}">

            {% include 'render_orders_item_shopper.html' %}
        </div>


    </div>


    {% block js %}
    <script src="{% static 'js/orders.js' %}"></script>

    {% endblock %}




    {% endautoescape %}