Shoppee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls',namespace='users')),
    path('orders/', include('apps.orders.urls',namespace='orders')),
    path('shop/', include('apps.shop.urls',namespace='shop')),
    path('cart/', include('apps.cart.urls',namespace='cart')),
    path('logs/', include('apps.logs.urls',namespace='logs')),
    path('login', views.LoginView.as_view(),name='login'),
    path('', views.home.as_view(),name='home'),
    path('profile', views.Profile.as_view(),name='profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/urls.py
from django.urls import path 
from . import views

app_name = 'apps.cart'

urlpatterns = [
    path('add-item/', views.add_cart_item, name='add_item'),
    path('items/', views.ajax_my_cart, name='my_cart_items'),
]

apps/shop/urls.py
from django.urls import path 
from . import views

app_name = 'apps.shop'

urlpatterns = [
    path('ajax-ads/', views.ajax_get_ads, name='ads'),
    path('ajax-items/', views.ajax_get_items, name='items'),
    path('ajax-item-edit/', views.ajax_get_edit_item, name='edit_item'),
    path('ajax-item-ads/', views.ajax_get_edit_ad, name='edit_ads'),
    path('ajax-item-update/', views.ajax_update_item, name='update_item'),
    path('ajax-item-delete/', views.ajax_delete_item, name='delete_item'),
    path('ajax-ad-delete/', views.ajax_delete_ad, name='delete_ad'),
    path('ajax-ad-update/', views.ajax_update_ad, name='update_ad'),
    path('ajax-items-owner/', views.ajax_get_items_owner, name='items_owner'),
    path('ajax-ads-owner/', views.ajax_get_items_owner, name='ads_owner'),
    path('ajax-create-ads/', views.ajax_craete_ads, name='create_ads'),
    path('ajax-create-item/', views.ajax_craete_item, name='create_item'),
    path('ajax-add-item-stock/', views.ajax_add_item_stock, name='add_item_stock'),
    path('items/', views.ItemsView.as_view(), name='items_view'),
    path('edit-items/', views.ajax_item_edit, name='edit_items'),
    path('edit-ads/', views.ajax_ads_edit, name='ads_items'),
    path('item/', views.ajax_get_item, name='item'),
]

apps/shop/models.py
from django.db import models

# Create your models here.

from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator
from Shoppee.models import BaseModel
from apps.users. models import MyCustomUser

class Shop(BaseModel):
    
    user = models.OneToOneField(
        MyCustomUser,
        related_name='shop',
        on_delete=models.CASCADE,
    )
    shop_name = models.CharField(max_length=20,blank = False, unique = True)
    
    def __str__(self):
        return f" {self.shop_name} - {self.user.full_name}"



class AdsCampaign(BaseModel):
    shop = models.ForeignKey(
        Shop,
        related_name='shop_ads',
        on_delete=models.CASCADE,
    )
    ads_description = models.CharField(max_length= 100)
    ads_name = models.CharField(max_length= 50, unique = True,blank=False)
    
    ads_image = models.ImageField(default='ad1.jfif', upload_to='Ads_Images')

    def __str__(self):
        return f"{self.shop} - {self.ads_name}"


class Item(BaseModel):
    shop = models.ForeignKey(
        Shop,
        related_name='items',
        on_delete=models.CASCADE,
    )
    name= models.CharField(max_length=50,blank=False)
    description= models.CharField(max_length=200)
    price = models.DecimalField(max_digits=20, default=0,decimal_places=2)
    stock = models.IntegerField(default=0)
    image = models.ImageField(default='item1',upload_to='Items')

    def __str__(self):
        return f"{self.name}"
    
    @property
    def get_short_desc(self):
        return f"{self.description[0:30]}..."
    
    @property
    def get_total_ordered(self):
        items = self.ordered_item.all()
        total = 0
        for item in items:
            if item.order.status == 'pending':
                total+= item.quantity
        return total
    
    
    @property
    def get_total_in_cart(self):
        items = self.cart_item.all()
        total = 0
        for item in items:
            total+= item.quantity
        return total
    @property
    def get_item_rating(self):
        rate = 0
        if not self.item_rating.all():
            return 0
        for item_rating in self.item_rating.all():
            rate += item_rating.rate
        return rate/len(self.item_rating.all())
    
class ItemRating(BaseModel):
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name='item_rating',
    )
    rate = models.FloatField(blank=False)
    user = models.ForeignKey(
        MyCustomUser,
        blank=False,
        on_delete=models.CASCADE,
    )
    comment = models.CharField(max_length=200,blank=True, null=True)

    def __str__(self):
        return f"{self.user.full_name} rated {self.item} {self.rate}"

apps/shop/forms.py
# forms.py
from django import forms
from .models import *
 

  
class AdsCampaignForm(forms.ModelForm):
 
    class Meta:
        model = AdsCampaign
        fields = [
            'ads_description',
            'ads_name',
            'ads_image',
        ]
     

apps/shop/views.py
from django.shortcuts import render, redirect
from .models import Shop,AdsCampaign,Item
from apps.users.models import MyCustomUser
from django.http import (HttpResponseRedirect, JsonResponse)
from django.contrib.auth.mixins import (LoginRequiredMixin, UserPassesTestMixin)
from django.views.generic.base import TemplateView

from django.http import HttpResponse
from .forms import *
from apps.cart.models import *
from apps.logs.views import *
from apps.logs.models import *

from django.template.loader import render_to_string
from django.db.models import Q
from PIL import Image
import io

# Create your views here.

def ajax_get_ads(request):
    
    
    if request.user.user_type == "seller":
        _id = request.user.id
        # _id = request.GET.get('user_id')
        user = MyCustomUser.objects.get(id = _id)
        shop = Shop.objects.get(user=user)
        ads = AdsCampaign.objects.filter(shop = shop,).order_by('?')[:10]
    else:

        ads = AdsCampaign.objects.all().order_by('?')[:5]
        


    htmlStr = render_to_string('render_campaign_ads.html', {
        'ads': ads,
    })
    
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
    })



def ajax_get_items(request):
    
    if request.user.user_type == "seller":
        _id = request.user.id
        user = MyCustomUser.objects.get(id = _id)
        shop = Shop.objects.get(user=user)
        items = Item.objects.filter(shop=shop).order_by('?')

    
    else:
        items = Item.objects.all().order_by('?')[:50]
    
    user = MyCustomUser.objects.get(id = request.user.id)

    htmlStr = render_to_string('render_items.html', {
        'items': items,
        'user': user
    })
    
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
    })

def ajax_get_edit_item(request):
    item = Item.objects.get(id = request.GET.get('item_id'))
    htmlStr = render_to_string('render_edit_item.html', {
        'item': item,
    })
    
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
    })

def ajax_get_edit_ad(request):
    item = AdsCampaign.objects.get(id = request.GET.get('item_id'))
    htmlStr = render_to_string('render_edit_ad.html', {
        'item': item,
    })
    
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
    })

def ajax_get_item(request):
    id = request.GET.get('item_id')
    item = Item.objects.get(id=id)
    htmlStr = render_to_string('render_item.html', {
        'item': item
    })
    
    if request.user == item.shop.user:
        htmlStr = render_to_string('render_item_add.html', {
        'item': item
        })
        
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
    })

def ajax_add_item_stock(request):

    if(not request.user.is_authenticated):
        return JsonResponse({'success': False,})
    # import pdb; pdb.set_trace()
    item_id = request.GET.get('item_id')
    try:
        quantity = int(request.GET.get('quantity'))
    except ValueError as ex:
        
        return JsonResponse({'success': False,
        'message':"Please input a number to be added to stock.",
        })
    if quantity<1:
        return JsonResponse({'success': True,
        'message':"Value for quantity cannot be less than or equal to 0.",
    })
    owner = MyCustomUser.objects.get(id=request.user.id)
    item = Item.objects.get(pk=item_id)
    current_stock = item.stock
    
    if not request.user == owner:
        return JsonResponse({'success': False,
        'message':"Failed to add stock.",
    })

    current_stock+= quantity
    item.stock = current_stock
    item.save()
    #send notification to shoppers with wishlists
    items = CartItem.objects.filter(item = item)
    for cart_item in items:
        cart_owner = cart_item.cart.owner
        send_notification(request.user,item,'Added stock to item',cart_owner,'common','')
        
    return JsonResponse({'success': True,
        'message':"Item stock successfully added.",
    })

def ajax_get_items_owner(request):
    serach = request.GET.get('search')

    
    _id = request.user.id
    user = MyCustomUser.objects.get(id = _id)
    shop = Shop.objects.get(user=user)
    items = Item.objects.filter(shop=shop).order_by('name')
    item_id = 1
    if serach:
        items = items.filter(Q(name__icontains=serach)|Q(description__icontains = serach))
    if items:
        item_id = items[0].id


    

    htmlStr = render_to_string('render_items_owner.html', {
        'items': items
    })
    
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
        'item_id':item_id,
    })

def handle_uploaded_image(file):
    img = Image.open(file)
    # Resize the image to your desired dimensions
    img.thumbnail((800, 800))
    # Save the image to a buffer
    buffer = io.BytesIO()
    img.save(buffer, format='JPEG', quality=50)
    # Set the file pointer at the beginning of the buffer
    buffer.seek(0)
    # Return the modified image buffer
    return buffer
 
def ajax_craete_ads(request):
 
    # form = AdsCampaignForm(request.POST, request.FILES)
 
    # if form.is_valid():
    #     # form.save()
    # import pdb;pdb.set_trace()
    
    _id = request.user.id
    user = MyCustomUser.objects.get(id = _id)
    shop = Shop.objects.get(user=user)
    ads_description =request.POST.get('ads_description')
    ads_name = request.POST.get('ads_name')
    ads_image =request.FILES.cleaned_data['file']
    processed_image = handle_uploaded_image(ads_image)
    AdsCampaign.objects.create(
            shop= shop,
            ads_name = ads_name,
            ads_description = ads_description,
            ads_image = processed_image
        )
        
    return JsonResponse({'success': True,})
    
        

 
def ajax_craete_item(request):
    
    _id = request.user.id
    user = MyCustomUser.objects.get(id = _id)
    shop = Shop.objects.get(user=user)
    name = request.POST.get('name')
    description = request.POST.get('description')
    price = request.POST.get('price')
    image = request.FILES['itemImage']

    Item.objects.create(
        shop=shop,
        name=name,
        description=description,
        price=price,
        image=image,
    )

    return JsonResponse({'success': True,})

def ajax_update_item(request):
    id = request.POST.get('item_id')
    item = Item.objects.get(id = id)
    item.name = request.POST.get('name')
    item.description = request.POST.get('desc')
    item.price = request.POST.get('price')

    file = request.FILES.get('i-editItemImage')
    if file:
        item.image = file
    item.save()


    
    return JsonResponse({'success': True,'message':'Item Updated.',})

def ajax_update_ad(request):
    id = request.POST.get('item_id')
    item = AdsCampaign.objects.get(id = id)
    item.ads_name = request.POST.get('name')
    item.ads_description = request.POST.get('desc')

    file = request.FILES.get('i-editItemImage')
    if file:
        item.ads_image = file
    item.save()

    print(item)

    
    return JsonResponse({'success': True,'message':'Ads Campaign Updated.',})
 
def success(request):
    return HttpResponse('successfully uplloaded')

class ItemsView(LoginRequiredMixin, TemplateView):
    template_name = 'items.html'
    
    def get_context_data(self, **kwargs):
    
        context = super(ItemsView, self).get_context_data(**kwargs)
        return context

def ajax_item_edit(request):
    shop = Shop.objects.get(user = request.user)
    items = Item.objects.filter(shop = shop)
    item_id = items[0].id

    htmlStr = render_to_string('render_items_view.html', {
        'items': items,
    })
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
        'item_id':item_id,
    })

def ajax_ads_edit(request):
    shop = Shop.objects.get(user = request.user)
    ads = AdsCampaign.objects.filter(shop = shop).order_by('ads_name')
    ad_id = ads[0].id

    htmlStr = render_to_string('render_ads_view.html', {
        'ads': ads,
    })
    return JsonResponse({
        'success': True,
        'htmlStr': htmlStr,
        'item_id':ad_id,
    })


def ajax_delete_item(request):
    item = Item.objects.get(id = request.POST.get('id'))
    if item:
        item.delete()
        return JsonResponse({
        'success': True,
        'message':'Item has been deleted.'
        })
    
    return JsonResponse({
        'success': True,
        'message':'There was an error deleting in item.'
    })
def ajax_delete_ad(request):
    item = AdsCampaign.objects.get(id = request.POST.get('id'))
    if item:
        item.delete()
        return JsonResponse({
        'success': True,
        'message':'Ad Campaign has been deleted.'
        })
    
    return JsonResponse({
        'success': True,
        'message':'There was an error deleting in Ad Campaign.'
    })

apps/shop/templates/create_ads.html
{% autoescape off %}



<form id="createAdsForm">
    {% csrf_token %}
    {{ form.as_p }}
</form>
<button id="createAds">Create</button>

{% endautoescape %}

apps/shop/templates/items.html
{% extends 'index.html' %}

{% load static %}
{% block title %}Items - Citi Hardware {% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/items.css' %}" type="text/css">
{% endblock %}

{% block body %}
<div
    style="position: absolute; top: 6vh; width: 100%; height: -webkit-fill-available;background-color: antiquewhite; padding: 20px; display: flex;">
    <div class="rightDiv" style="height: 100%;width: 70%; background-color: cadetblue;">

        <div style="
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
        border: 3px solid green; ">

            <div class="loader">

            </div>
        </div>

    </div>
    <div class="leftDiv"
        style="height: 100%;width: 30%; overflow-y: scroll; background-color: rgb(129, 129, 184); margin-left: 20px;">
        <div class="title">Shop Items</div>
        <div class="itemsContainer" id="itemsContainer" data-ajax-url="{% url 'shop:items_owner' %}" data-ajax-url-edit="{% url 'shop:edit_item' %}">


        </div>
    </div>

</div>

{% endblock %}
{% block js %}
<script src="{% static 'js/item_owner.js' %}"></script>

{% endblock %}

apps/shop/templates/render_ads_owner.html
{% autoescape off %}
{% load static %}
{% if ads.all %}
{% for item in ads.all %}


<div class="itemDiv" onclick="editAds('{{ item.id }}')" >
    <div class="image">
        <img src="{{ item.ads_image.url }}" alt="Image" style="height: 30px; width: 30px;">
    </div>
    <h4  style="cursor: pointer;">{{ item.ads_name }}</h4>
</div>



{% endfor %}

{% else %}
<p colspan="5">No Data</p>
{% endif %}
{% endautoescape %}

apps/shop/templates/render_ads_view.html
{% autoescape off %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static 'css/items.css' %}" type="text/css">
{% endblock %}


<div style="position: absolute; top: 6vh; width: 100%; height: -webkit-fill-available;background-color: antiquewhite; padding: 20px; display: flex;">
    <div class="leftDiv"style="height: 100%;width: 25%; overflow-y: scroll; background-color: rgb(129, 129, 184);margin: auto; margin-right: 20px;">
        <div class="title" style="height: 46px; ">
            <form >
            <input type="text" name="search" placeholder="Search Ads.." class="searchItems">
          </form>
        </div>
        <div class="itemsContainer" id="itemsContainer" data-ajax-url-edit="{% url 'shop:edit_ads' %}">
            {% include 'render_ads_owner.html' %}

        </div>
    </div>
    <div class="rightDiv" style="height: 100%;width: 70%; background-color: cadetblue; margin: auto; margin-left: 10px; padding: 20px; overflow-y: scroll;">

        <div style="
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
        border: 3px solid green; ">

            <div class="loader">

            </div>
        </div>

    </div>

</div>


{% block js %}
<script src="{% static 'js/ads_owner.js' %}"></script>

{% endblock %}




{% endautoescape %}

apps/shop/templates/render_campaign_ads.html
{% autoescape off %}
{% load static %}
{% if ads.all %}

<div style="margin: auto;">
    {% for ad in ads.all %}

    <div class="mySlides fade">
        <img src="{{ ad.ads_image.url }}">
    </div>
    {% endfor %}

    <!-- <a class="prev" >&#10094;</a>
    <a class="next" >&#10095;</a> -->
</div>
<br>
<div style="text-align:center; top:37vh;position: initial;width: 100%; transform: translateY(-45px);">
    {% for ad in ads.all %}
    
    <span class="dot" ></span>
    {% endfor %}
</div>
{% else %}
<p colspan="5">No Data</p>
{% endif %}
{% endautoescape %}

apps/shop/templates/render_edit_ad.html
{% autoescape off %}
{% load static %}
{% block css %}


<link rel="stylesheet" href="{% static 'css/edit_item.css' %}">
{% endblock %}


<div class="editItemContainer">
    <div class="editItemTitle">

    </div>
    <div class="editItemFormContainer" style="display: flex;flex-direction: column; height: 100%;  margin: auto; width: 90%;">
        <img src="{{ item.ads_image.url }}" alt="Item Image" style="width: 100%; height: auto; margin: auto; margin-top: 20px;">
        <h2 style="text-align: center;">{{ item.ads_name }}</h2>
        <form data-ajax-item-id="{{ item.id }}" style="display: contents; " id="formEditAd" data-ajax-url="{% url 'shop:update_ad' %}" enctype="multipart/form-data">
            <label for="editItemImage">Upload new Image:</label>
            <input type="file" alt="" name="i-editItemImage" id="i-editItemImage">
            <label for="name">Item Name:</label>
            <input  type="text" name="name" id="name" value="{{ item.ads_name }}">
            <label for="desc">Description:</label>
            <textarea name="desc" id="desc" rows="5" cols="30">{{ item.ads_description }}</textarea>
            <input type="submit" value="Update Ads Campaign" style="padding: 10px;">
        </form>
        <button style="padding: 10px;" data-ajax-url="{% url 'shop:delete_ad' %}" id="deleteAd">Delete Ads Campaign</button>
        <button style="padding: 10px; margin-top: 20px;"  id="createAdsBtn">New Ads Campaign</button>
    </div>
</div>


{% block js %}

{% endblock %}

{% endautoescape %}

apps/shop/templates/render_edit_item.html
{% autoescape off %}
{% load static %}
{% block css %}


<link rel="stylesheet" href="{% static 'css/edit_item.css' %}">
{% endblock %}


<div class="editItemContainer">
    <div class="editItemTitle">

    </div>
    <div class="editItemFormContainer" style="display: flex;flex-direction: column; height: 100%;  margin: auto; width: 90%;">
        <img src="{{ item.image.url }}" alt="Item Image" style="width: 35%; height: auto; margin: auto; margin-top: 20px;">
        <h2 style="text-align: center;">{{ item.name }}</h2>
        <form data-ajax-item-id="{{ item.id }}" style="display: contents; " id="formEditItem" data-ajax-url="{% url 'shop:update_item' %}" enctype="multipart/form-data">
            <label for="editItemImage">Upload new Image:</label>
            <input type="file" alt="" name="i-editItemImage" id="i-editItemImage">
            <label for="name">Item Name:</label>
            <input type="text" name="name" id="name" value="{{ item.name }}">
            <label for="desc">Description:</label>
            <textarea name="desc" id="desc" rows="5" cols="30">{{ item.description }}</textarea>
            
            <label for="price">Item Price:</label>
            <input type="text" name="price" id="price" value="{{ item.price }}">
            <h4>Stock: {{ item.stock }} (You can edit this space in add item stock)</h4>
            <input type="submit" value="Update Item" style="padding: 10px;">
        </form>
        <button id="deleteItem" style="padding: 10px;" data-ajax-url="{% url 'shop:delete_item' %}">Delete Item</button>
        <button  style="padding: 10px; margin-top: 30px;" id="myBtn">New Item</button>
    </div>
</div>


{% block js %}

{% endblock %}

{% endautoescape %}

apps/shop/templates/render_item.html
{% autoescape off %}
{% load static %}





<div style="width: 100%; ; background-color: red;">
    <img src="{{ item.image.url }}" alt="Item Image" style="width: 100%; height: auto;">
</div>
<div class="info" style="width: 100%; height: auto; padding: 10px; background-color: aqua; ">
    <h5 style="color: black; font-weight: bold; font-size: 15px; font-family: Arial, Helvetica, sans-serif;">{{ item.name }}</h5>
    <small style="color: black; overflow: hidden; font-size: 12px;">{{ item.description }}</small>
    <div>
        <small style="color: black;width: 100%;">Price: &dollar;{{ item.price }}</small>
        <small style="color: black; margin-left: 5px;">Stock: {{item.stock}}</small>
    </div>
    <input style="width: 150px;" type="number" name="quantity" id="quantity" value="1" max="{{ item.stock }}" min="1">
    <br>
    {% if item.stock == 0 %}
    <button style="width: 150px;" data-ajax-url="{% url 'cart:add_item' %}" data-ajax-item-id="{{ item.id }}" id="submitAddToCart" onclick="">Add To Wishlist</button>
    {% else %}
    <button style="width: 150px;" data-ajax-url="{% url 'cart:add_item' %}" data-ajax-item-id="{{ item.id }}" id="submitAddToCart" onclick="">Add To Cart</button>
    {% endif %}
    <br>
    <button style="width: 150px;">More Info</button>
</div>


{% endautoescape %}

apps/shop/templates/render_item_add.html
{% autoescape off %}
{% load static %}





<div style="width: 100%; ; background-color: red;">
    <img src="{{ item.image.url }}" alt="Item Image" style="width: 100%; height: auto;">
</div>
<div class="info" style="width: 100%; height: auto; padding: 10px; background-color: aqua; ">
    <h5 style="color: black; font-weight: bold; font-size: 15px; font-family: Arial, Helvetica, sans-serif;">{{ item.name }}</h5>
    <small style="color: black; overflow: hidden; font-size: 12px;">{{ item.description }}</small>
    <div>
        <small style="color: black;width: 100%;">Price: &dollar;{{ item.price }}</small>
        <small style="color: black; margin-left: 5px;">Stock: {{item.stock}}</small>
    </div>
    <input style="width: 150px;" type="number" name="quantity" id="quantity"  placeholder="Quantity to be added...">
    <br>
    <button style="width: 150px;" data-ajax-url="{% url 'shop:add_item_stock' %}" data-ajax-item-id="{{ item.id }}" id="submitAddStock" onclick="">Add To Stock</button>
    <br>
    <button style="width: 150px;">More Info</button>
</div>


{% endautoescape %}

apps/shop/templates/render_items.html
{% autoescape off %}
{% load static %}
{% block css %}


<link rel="stylesheet" href="{% static 'css/shopper.css' %}">
{% endblock %}




{% if items.all %}
    <!-- dito ang add to cart modal  -->
    <div class="addToCartModal" id="addToCartModal">
        <div class="modal-content">
            <div style=" text-align: end;">
                <span class="closeAddToCart" style="color: black; cursor: pointer;">&times;</span>
            </div>
                <div class="informationDiv" id="informationDiv">
                    <div id="loader" style="display: flex;justify-content: center;align-items: center;height: 600px; ">
                        <div class="loader">
                        </div>
                    </div>
                </div>
            
        </div>

    </div>
{% for item in items.all %}

<div class="card">
    <div style="border: solid 1px black;">
        <img src="{{ item.image.url }}" alt="" style="width: 200px; height: auto;">
        <div style="height: 80px; width: 100%;background-color: azure; text-align: left; padding: 5px;">
            <h5 style="color: black; font-weight: bold; font-size: 15px; font-family: Arial, Helvetica, sans-serif;">{{ item.name|truncatechars:22 }}</h5>
            <small style="color: black; overflow: hidden; font-size: 12px;">{{ item.description|truncatechars:30 }}</small>
            <div>
                <small style="color: black;width: 100%;">&dollar;{{ item.price }}</small>
                <small style="color: black; margin-left: 5px;" >Stock: {{item.stock}}</small>
                <small style="color: black; margin-left: 5px;" >Rating: {{item.get_item_rating}}</small>
            </div>
            {% if user == item.shop.user %}
            <button style="width: 100%;" onclick="openAddStock('{{ item.id }}')">Add To Stock</button>
            {% else %}
            <button style="width: 100%;" id="btnAddToCart" onclick="openAddToCart('{{ item.id }}')">Add To Cart</button>

            
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
<div class="container" style="color: black;">
    <div class="row">
      {% for item in items %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top border" src="{{ item.image.url }}" alt="{{ item.name }}">
          <div class="card-body">
            <h5 class="card-title">{{ item.name|truncatechars:30 }}</h5>
            <p class="card-text">{{ item.description|truncatechars:40 }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted">Ratings: {{ item.get_item_rating }}</small>
            </div>
            <a href="#" class="btn btn-primary">View details</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

{% else %}
<p colspan="5">No Data</p>
{% endif %}
{% block js %}
{% if user.user_type == 'shopper' %}
    <script src="{% static 'js/shopper.js' %}"></script>
{% else %}
    <script src="{% static 'js/seller.js' %}"></script>
{% endif %}
{% endblock %}

{% endautoescape %}

apps/shop/templates/render_items_owner.html
{% autoescape off %}
{% load static %}
{% if items.all %}
{% for item in items.all %}


<div class="itemDiv" onclick="editItem('{{ item.id }}')">
    <div class="image">
        <img src="{{ item.image.url }}" alt="Image" style="height: 30px; width: 30px;">
    </div>
    <h4  style="cursor: pointer;">{{ item.name }}</h4>
</div>



{% endfor %}

{% else %}
<p colspan="5">No Data</p>
{% endif %}
{% endautoescape %}

apps/shop/templates/render_items_view.html
{% autoescape off %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static 'css/items.css' %}" type="text/css">
{% endblock %}
<div
    style="position: absolute; top: 6vh; width: 100%; height: -webkit-fill-available;background-color: antiquewhite; padding: 20px; display: flex; margin: auto;">
    
    <div class="leftDiv"
        style="height: 100%;width: 25%; overflow-y: scroll; background-color: rgb(129, 129, 184);margin: auto; margin-right: 20px;">
        <div class="title" style="height: 46px;">
            <input type="text" name="search" id="searchItems" placeholder="Search Items.." class="searchItems" onkeydown="loadItemOwnerSearch()">
          </div>
        <div class="itemsContainer" id="itemsContainer" data-ajax-url="{% url 'shop:items_owner' %}" data-ajax-url-edit="{% url 'shop:edit_item' %}">


        </div>
    </div>
    <div class="rightDiv" style="height: 100%;width: 60%; background-color: cadetblue; margin: auto;margin-left: 10px;">

        <div style="
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100%;
        border: 3px solid green; ">

            <div class="loader">

            </div>
        </div>

    </div>

</div>


{% block js %}
<script src="{% static 'js/item_owner.js' %}"></script>

{% endblock %}




{% endautoescape %}