Shoppee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls',namespace='users')),
    path('orders/', include('apps.orders.urls',namespace='orders')),
    path('shop/', include('apps.shop.urls',namespace='shop')),
    path('cart/', include('apps.cart.urls',namespace='cart')),
    path('logs/', include('apps.logs.urls',namespace='logs')),
    path('login', views.LoginView.as_view(),name='login'),
    path('', views.home.as_view(),name='home'),
    path('profile', views.Profile.as_view(),name='profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/urls.py
from django.urls import path 
from . import views

app_name = 'apps.shop'

urlpatterns = [
    path('ajax-ads/', views.ajax_get_ads, name='ads'),
    path('ajax-items/', views.ajax_get_items, name='items'),
    path('ajax-item-edit/', views.ajax_get_edit_item, name='edit_item'),
    path('ajax-item-ads/', views.ajax_get_edit_ad, name='edit_ads'),
    path('ajax-item-update/', views.ajax_update_item, name='update_item'),
    path('ajax-item-delete/', views.ajax_delete_item, name='delete_item'),
    path('ajax-ad-delete/', views.ajax_delete_ad, name='delete_ad'),
    path('ajax-ad-update/', views.ajax_update_ad, name='update_ad'),
    path('ajax-items-owner/', views.ajax_get_items_owner, name='items_owner'),
    path('ajax-ads-owner/', views.ajax_get_items_owner, name='ads_owner'),
    path('ajax-create-ads/', views.ajax_craete_ads, name='create_ads'),
    path('ajax-create-item/', views.ajax_craete_item, name='create_item'),
    path('ajax-add-item-stock/', views.ajax_add_item_stock, name='add_item_stock'),
    path('items/', views.ItemsView.as_view(), name='items_view'),
    path('edit-items/', views.ajax_item_edit, name='edit_items'),
    path('edit-ads/', views.ajax_ads_edit, name='ads_items'),
    path('item/', views.ajax_get_item, name='item'),
]

apps/users/urls.py
from django.urls import path 
from . import views


app_name = 'apps.users'

urlpatterns = [
    path('login/',views.loginUser, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('ajax_register/', views.ajax_register, name='register'),
]

apps/users/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from .helpers import optional, USER_TYPE_CHOICES,GENDER_CHOICES
from django.utils.translation import gettext_lazy as _
from Shoppee.managers import CustomUserManager
from django.core.validators import RegexValidator
from Shoppee.models import BaseModel


class MyCustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=50, blank=False)
    middle_name = models.CharField(max_length=50, **optional)
    last_name = models.CharField(max_length=50, blank=False)
    extension = models.CharField(max_length=50,**optional)
    email = models.EmailField(unique=True)
    username= models.CharField(_('Username'),max_length=100,blank=False,unique= True)
    user_type = models.CharField(max_length=10,choices=USER_TYPE_CHOICES,default='shopper')

    
    is_superadmin = models.BooleanField(_('is_superadmin'), default=False)
    is_active = models.BooleanField(_('is_active'), default=False)
    is_staff = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS =[
        'first_name',
        'last_name',
        'email',

    ]

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return f"{self.username}({self.user_type})"

    @property
    def full_name(self):
        return f"{self.first_name} {self.middle_name if self.middle_name else ''} {self.last_name} {self.extension if self.extension else ''}"

class UserInformation(BaseModel):
    user = models.OneToOneField(
        MyCustomUser,
        related_name='user_information',
        on_delete=models.CASCADE,
        unique=True,
    )
    mobile_regex = RegexValidator(regex=r'^(\+\d{1,3})?,?\s?\d{8,13}', message="Mobile number format must be: '+639999999999'.")
    phone_number = models.CharField(validators=[mobile_regex], max_length=20,unique=True)
    gender = models.CharField(max_length=20,**optional,choices=GENDER_CHOICES)
    address = models.CharField(max_length=200,**optional)
    #address-
    #contact-
    #telephone
    #facebook
    #website
    #
    #

    
    def __str__(self):
        return f"{self.user.full_name}"


    @property
    def get_user_id(self):
        return self.user.id

apps/users/forms.py
from apps.users.models import MyCustomUser
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.template.loader import render_to_string


class LoginForm(forms.Form):
    """user login form"""
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'required': True,
        'autofocus': True
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        'required': True
    }))
    remember_me = forms.BooleanField(required=False)

apps/users/views.py
from django.shortcuts import render

from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from django.http import (HttpResponseRedirect, JsonResponse)

from django.views.generic.edit import FormView, UpdateView
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from .forms import LoginForm
from .models import MyCustomUser
from django.contrib.auth.mixins import (LoginRequiredMixin, UserPassesTestMixin)
from apps.cart.models import Cart
from django.template.loader import render_to_string
# Create your views here.


def loginUser(request):
    return render(request, 'login.html')


class LoginView(FormView):
    
    form_class = LoginForm
    template_name  = 'login.html'

    def get(self, request, *args, **kwargs): 
        if request.user.is_authenticated:
            return HttpResponseRedirect('/admin')                                           #redirect if user is logged in
        return super(LoginView, self).get(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        # user = self.request.user
        return ('/')
    
    def post(self, request, *args,**kwargs):
        username = request.POST.get('username')
        try:
            user = MyCustomUser.objects.get(username=username)
        except MyCustomUser.DoesNotExist:
            messages.error(self.request, 'No user found')
            return HttpResponseRedirect('/')
        return super(LoginView, self).post(request, *args, **kwargs)    

    def form_invalid(self, form):
        for key, value in form.errors.items():
            for msg in value:
                messages.error(self.request, f"{key}: {msg}")

        return super(LoginView, self).form_invalid(form)
    
    def form_valid(self, form):
        """ process user login"""
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None:
            if user.is_active:
                login(self.request, user)
                self.request.session.set_expiry(1000)
                if form.cleaned_data['remember_me']:
                    self.request.session.set_expiry(1209600)
                return HttpResponseRedirect(self.get_success_url())
            else:
                messages.error(self.request, 'Please activate your account.')
        else:
            messages.error(self.request, 'Please check your credentials')

        return HttpResponseRedirect('/')
        #return super(LoginView, self).form_invalid(form)

class home(LoginRequiredMixin,TemplateView):
    template_name = 'home.html'
    
    def get_context_data(self, **kwargs):
    
        context = super(home, self).get_context_data(**kwargs)
        return context
    
class Profile(LoginRequiredMixin,TemplateView):
    template_name = 'profile.html'
    
    def get_context_data(self, **kwargs):
    
        context = super(Profile, self).get_context_data(**kwargs)
        return context
    
def Logout(request):
    """logout logged in user"""
    logout(request)
    return HttpResponseRedirect('/login')

def ajax_register(request):
    
    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    email = request.GET.get('email')
    username = request.GET.get('username')
    password = request.GET.get('password')

    data = {
        'first_name':first_name,
        'last_name':last_name,
        'email':email,
        'username':username,
        'is_active':True,
    }

    MyCustomUser.objects.create(**data)
    user = MyCustomUser.objects.get(**data)
    
    user.set_password(password)
    user.save()
    
    cart_data = {
        'owner' : user,
        'name': 'Cart'
    }
    #create cart for new user
    Cart.objects.create(**cart_data)

    return JsonResponse({
        'success': True,
    })

apps/users/templates/home.html
{% extends 'index.html' %}

{% load static %}
{% block title %} Citi Hardware {% endblock %}

{% block css %}

<link href="{% static 'css/popup.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
{% if user.user_type == 'seller' %}
<div id="myModal" class="modal" data-ajax-url="{% url 'shop:create_item' %}">
    <div class="modal-content">
        <div style=" text-align: end;">
            <span class="close">&times;</span>
        </div>
        <div class="form">
            <h2>Add New Item</h2>
            <div style="text-align: left;">
                <form id="upload-Item" enctype="multipart/form-data">
                    {% csrf_token %}

                    <label for="itemName">Item Name</label>
                    <input type="text" name="itemName" id="itemName" style="width: 100%;">
                    <label for="description">Desription</label>
                    <input type="text" name="description" id="description" style="width: 100%;">
                    <label for="price">Price</label>
                    <input type="text" name="price" id="price" style="width: 100%;">
                    <label for="imgInp">Item Image</label>
                    <br>
                    <input type="file" src="" alt="" name="itemImage" accept="image/*" id="imgInp">
                    <br>

                    <img id="blah" src="#" alt="Image Preview" /
                        style="    width: -webkit-fill-available;height: auto;">
                    <br>
                    <button type="submit" class="btn btn-success">Upload</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="myModal1" class="modal" data-ajax-url="{% url 'shop:create_ads' %}" data-csrf-token="{{ csrf_token }}">
    <div class="modal-content">
        <div style=" text-align: end;">
            <span class="close">&times;</span>
        </div>
        <div class="form" id="form">
            <h2>Add New Ads Campaign</h2>

            <form id="upload-file" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="ads_name">Campaign Name</label>
                <input type="text" name="ads_name" id="ads_name" style="width: 100%;">
                <label for="ads_description">Desription</label>
                <input type="text" name="ads_description" id="ads_description" style="width: 100%;">
                <label for="ads_image">Ads Image</label>
                <br>
                <input type="file" name="file" id="imgInput">
                <br>
                <img id="preview1" src="#" alt="Image Preview" /
                    style="    width: -webkit-fill-available;height: auto;">
                <br>
                <button type="submit" class="btn btn-success">Upload</button>
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

{% block body %}
    <div id="main1" style="position: absolute; top: 6vh; width: 100%; display: flex; ">
        <!-- space for adds -->
        {% if user.user_type == 'shopper' %}
        <div
            style="width: 25%; height: 92vh; background-color: wheat; margin: auto; margin-top: 0px; position: sticky; top: 6vh;">
            dito ang Categories
        </div>
        {% endif %}
        <div style="width: 70%; overflow-x: hidden; margin: auto; overflow-y: scroll; height: 92vh;">
            <div style="height: 40vh ; background-color: chocolate; text-align: center; margin: auto;" id="adsDiv"
                data-ajax-url="{% url 'shop:ads' %}" data-ajax-User-id="{{ user.id }}">
                {% block ads %}
                {% endblock %}
            </div>
            <div style="height: auto; width: 100%; background-color: aquamarine;text-align: center;">

                <div class="slideshow-container" id="slideContainer" style="text-align: center;">
                    <h1 style="padding-top: 50px;">Shop Products</h1>
                </div>

                <div class="cardContainer" id="cardContainer" data-ajax-url="{% url 'shop:items' %}">


                </div>


            </div>
        </div>
    </div>


{% endblock %}
{% block js %}
<script src="{% static 'js/popup-home.js' %}"></script>
{% if user.user_type == 'seller' %}
<script src="{% static 'js/shop.js' %}"></script>
{% endif %}
<script src="{% static 'js/ads.js' %}"></script>
{% endblock %}

apps/users/templates/login.html
{% extends 'index.html' %}

{% block title %} Login {% endblock %}
{% load static %}

{% block css %}
<link href="{% static 'css/popup.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block body %}



<div id="myModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <div class="content">
      <div class="container">
        <div class="row" style="
      text-align: -webkit-center;">
          <!-- <div class="col-md-6">
          <img src="{% static '/images/undraw_remotely_2j6y.svg' %}" alt="Image" class="img-fluid">
        </div> -->
          <div class="contents"
            style="width: 300px; border: solid white 30px; background-color: white; border-radius: 10px;">
            <div class="row justify-content-center">
              <div class="col-md-8">
                <div class="mb-4">
                  <h3>Sign In</h3>
                  <p class="mb-4">Login to start shopping.</p>
                </div>
                <form action="#" method="post">
                  {% csrf_token %}
                  <div class="form-outline mb-2" style="display: grid; text-align: left;">
                    <label class="form-label" for="username">Username</label>
                    <input type="text" id="username" name="username" class="control" placeholder="Username" />
                  </div>
                  <div class="input-group input-group-lg form-outline mb-4" style="display: grid; text-align: left;">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" id="password" name="password" class="control" placeholder="Password" />
                    <!-- <span class="see-password input-group-text" id="basic-addon2"><a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a></span> -->
                  </div>

                  <div class="d-flex mb-3 align-items-center" style="display: grid; text-align: left;">
                    <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                      <input type="checkbox" name="remember_me" />
                      <div class="control__indicator"></div>
                    </label>
                    <span class="ml-auto">
                      <a href="#" class="forgot-pass">Forgot Password</a></span>
                  </div>
                  <div style="display: grid;text-align: center;">

                    <input type="submit" value="Sign In" class="btn btn-primary w-100 mb-1">
                    <span class="w-100 text-muted">&mdash; or login with &mdash;</span>
                    <a class="w-100 mt-3 btn btn-light disabled" style="vertical-align: bottom; color: #dd4b39;">
                      <i class="fab fa-lg fa-google"></i>Google
                    </a>
                  </div>
                </form>
                <div class="mt-1">
                  <p class="mb-4">Register now! To start your shopping</p>
                  <div class="w-100 text-center">
                    <a class="btn btn-outline-primary btn-rounded waves-effect" role="button">Register</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<div id="registerModal" class="registerModal">

  <div class="modal-content">
    <span class="close">&times;</span>
    <div class="content" data-ajax-url="{% url 'users:register' %}" id="registerDiv">
      <div class="container container-register">
        <form id = "registerForm">
          {% csrf_token %}
          <h2>Registration</h2>
          <label for="email">E-mail</label>
          <input type="email" name="email" id="emailreg">
          <br>
          <label for="username">Username</label>
          <input type="text" name="username" id="usernamereg">
          <br>
          <label for="firstName">First name</label>
          <input type="text" name="firstName" id="fName">
          <br>
          <label for="lastName">Last name</label>
          <input type="text" name="lastName" id="lName">
          <br>
          <label for="password">Password</label>
          <input type="password" name="password" id="passwordreg">
        </form>
          <input id="submmitReg" type="submit" value="Register" style="border: solid 1px black; border-radius: 5px;">
        <p>Already have an account? <a href="">Sign in</a></p>
      </div>
    </div>
  </div>

</div>

<div style="position: absolute; top: 6vh; width: 100%;">
  <!-- space for adds -->
  <div style="height: 60vh ; background-color: chocolate; text-align: center; margin: auto;">
      {% block ads %}
      <div style="margin: auto;">

          
          <div class="mySlides fade">
              <img src="{% static '/images/ad1.jfif' %}">
              <div class="text">Tables for all occassions.</div>
          </div>

          <div class="mySlides fade">
              <img src="{% static '/images/ad2.jfif' %}">
              <div class="text">Storage for everyone.</div>
          </div>

          <div class="mySlides fade">
              <!-- <div class="numbertext">3 / 3</div> -->
              <img src="{% static '/images/ad3.jfif' %}">
              <div class="text">Appliances and tools for everyday needs.</div>
          </div>

          <!-- Next and previous buttons -->
          <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <br>

      <div style="text-align:center">
          <span class="dot" onclick="currentSlide(1)"></span>
          <span class="dot" onclick="currentSlide(2)"></span>
          <span class="dot" onclick="currentSlide(3)"></span>
      </div>
      {% endblock %}
  </div>
  <div class="slideshow-container">
      <!-- Full-width images with number and caption text -->

  </div>
</div>




{% endblock %}
{% block js %}
<script src="{% static 'js/popup.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>

{% if messages %}
  {% for message in messages %}
  <script>
    var loginMessage = '{{ message }}'
    openMessageModal(loginMessage)
  </script>
  {% endfor %}
{% endif %}


{% endblock %}

apps/users/templates/profile.html
{% extends 'index.html' %}

{% block title %} Profile {% endblock %}
{% load static %}


{% block css %}

{% endblock %}
{% block body %}


<div>
    Profile Page
</div>




{% endblock %}