Shoppee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls',namespace='users')),
    path('orders/', include('apps.orders.urls',namespace='orders')),
    path('shop/', include('apps.shop.urls',namespace='shop')),
    path('cart/', include('apps.cart.urls',namespace='cart')),
    path('logs/', include('apps.logs.urls',namespace='logs')),
    path('login', views.LoginView.as_view(),name='login'),
    path('', views.home.as_view(),name='home'),
    path('profile', views.Profile.as_view(),name='profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/urls.py
from django.urls import path 
from . import views

app_name = 'apps.shop'

urlpatterns = [
    path('ajax-ads/', views.ajax_get_ads, name='ads'),
    path('ajax-items/', views.ajax_get_items, name='items'),
    path('ajax-item-edit/', views.ajax_get_edit_item, name='edit_item'),
    path('ajax-item-ads/', views.ajax_get_edit_ad, name='edit_ads'),
    path('ajax-item-update/', views.ajax_update_item, name='update_item'),
    path('ajax-item-delete/', views.ajax_delete_item, name='delete_item'),
    path('ajax-ad-delete/', views.ajax_delete_ad, name='delete_ad'),
    path('ajax-ad-update/', views.ajax_update_ad, name='update_ad'),
    path('ajax-items-owner/', views.ajax_get_items_owner, name='items_owner'),
    path('ajax-ads-owner/', views.ajax_get_items_owner, name='ads_owner'),
    path('ajax-create-ads/', views.ajax_craete_ads, name='create_ads'),
    path('ajax-create-item/', views.ajax_craete_item, name='create_item'),
    path('ajax-add-item-stock/', views.ajax_add_item_stock, name='add_item_stock'),
    path('items/', views.ItemsView.as_view(), name='items_view'),
    path('edit-items/', views.ajax_item_edit, name='edit_items'),
    path('edit-ads/', views.ajax_ads_edit, name='ads_items'),
    path('item/', views.ajax_get_item, name='item'),
]

apps/users/urls.py
from django.urls import path 
from . import views


app_name = 'apps.users'

urlpatterns = [
    path('login/',views.loginUser, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('ajax_register/', views.ajax_register, name='register'),
]

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}{% endblock %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">  -->

    <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %}{% endblock %}</title>
</head>

<body style="background-color: brown;">
    <h6 id="token" hidden data-csrf-token="{{ csrf_token }}"></h6>
    {% block navbar %}
    <div class="navbar" id="navbar"
        style="height: 4vh;background-color: red;  font-size: 29px; font-weight: bold; margin :10px;margin-left: 20px; margin-right: 20px; padding-left: 20px; display: flex;  font-family: sans-serif;">
        <div
            style=" transform: rotate(-15deg);width: min-content; display: block; border: solid 1px white; background-color: red;">
            <a href="/" style="text-decoration: none; color: white;">Citi</a>
            <p
                style="font-size: 4px; color: white; margin: 0; text-align: right; translate: 22px;font-weight: normal; position: fixed; top: 26px;">
                HARDWARE</p>
        </div>
        <div style="width: max-content; margin: auto; font-size: 12px; margin-right: 10px;" id="navbar1">

            {% if user.is_authenticated %}
            <i class="fa fa-search"></i>
            <input type="text" style="margin-right: 10px; width: 30vw; padding: 5px; border-radius: 5px; border: none;">
            <a id="shopNav" class="menuItem" href="/"
                style="text-decoration: none; color: white; margin-right: 15px;"><i class="fa fa-home"></i></a>
            {% if user.user_type == "seller" %}
            <a id="viewItemsNav" onclick="viewAllItems()" class="menuItem"
                style="text-decoration: none; color: white; margin-right: 15px;cursor: pointer;"><i
                    class="fa fa-industry"></i> View Shop Items</a>
            <a class="menuItem" onclick="viewAllAds()"
                style="text-decoration: none; color: white; margin-right: 15px; cursor: pointer;"><i
                    class="fa fa-buysellads"></i> View Shop Ads</a>
            <a class="menuItem" onclick="viewOrders('pending')" id="ordersBtn"
                style="text-decoration: none; color: white; margin-right: 15px; cursor: pointer;">Orders
            </a>
            {% else %}

            <a class="menuItem" onclick="viewOrders('pending')"
                style="text-decoration: none; color: white; margin-right: 15px">My Orders</a>

            <a id="cartNavButton" class="menuItem" onclick="myCart()"
                style="text-decoration: none; color: white; margin-right: 15px; cursor: pointer; position: relative;display: inline-block;padding: 10px 10px;"><i
                    class="fa fa-shopping-cart"></i><span class="badge">{{ user.cart.cart_items.all|length }}</span></a></a>
            {% endif %}
            <a id="shopNav" class="menuItem notification" onclick="openNotification()"
                style="text-decoration: none; color: white; margin-right: 15px;">
                <span><i class="fa fa-bell"></i></span>
                <span class="badge" id="notificationBadge"></span>
            </a>
            <a class="menuItem" href="{% url 'profile' %}" style="text-decoration: none; color: white; margin-right: 15px"><i
                    class="fa fa-user"></i> ({{user.full_name}})</a>

            <a href="{% url 'users:logout' %}" style="text-decoration: none; color: white; margin-right: 15px"><i
                    class="fa fa-user"></i> Logout</a>
            {% else %}

            <button id="registerButton"
                style="text-decoration: none; color: white; margin-right: 15px; border: none; background-color: transparent; cursor: pointer;">Register</button>
            <button id="myBtn"
                style="text-decoration: none; color: white; margin-right: 15px; border: none; background-color: transparent; cursor: pointer;">Login</button>
            {% endif %}
        </div>
    </div>
    {% endblock navbar %}

    {% block content %}
    {% endblock content %}
    <div id="main">
        <div class="body" id="body">
            {% block body %}
            {% endblock body %}
        </div>
    </div>
    <div id="mySidenav" class="sidenav" >
        <div style="text-align: center;">
            <a style="cursor: pointer;" class="closebtn" onclick="closeNotification()">&times;</a>
            <h2 style="text-align: center;">Notification</h2>
            <button onclick="mark_all_as_read()" style="margin: auto; padding: 5px; padding-left: 20px; padding-right: 20px;" >Mark all as READ</button>
        </div >
        <div id="notificationView" style="display: flex; flex-direction: column; overflow-y: scroll; height: 85%;">

        </div>
    </div>
    <div id="messageModal" class="messageModal">
        <div class="modal-content" style="margin-top: 30vh;">
            <h3 style="text-align: center;">Message</h3>
            <p id="message">This is My message</p>
            <div style=" text-align: end;">
                <button id="closeMessage">Close</button>
            </div>
        </div>
    </div>

    <div id="messageModalPrompt" class="messageModal">
        <div class="modal-content" style="margin-top: 30vh;">
            <h3 style="text-align: center;"><i class="fa fa-warning"></i> Warning</h3>
            <p style="margin-top: 30px; margin-bottom: 30px;" id="messagePrompt">This is My message</p>
            <div style=" text-align: end; display: flex;">
                <button id="promptProceed"
                    style="width: 50%; padding: 12px; margin: 5px; background-color: #f44336; color: white; border: none;">Proceed</button>
                <button id="closeMessagePrompt"
                    style="width: 50%; padding: 12px; margin: 5px;background-color: #ccc;color: black; border: none;">Cancel</button>
            </div>
        </div>
    </div>

    {% block footer %}
    {% endblock footer %}

</body>

<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"></script>

<!-- Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

<!-- jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block js %}{% endblock %}

</html>

templates/publications.html
{% extends 'index.html' %}

{% load static %}
{% block title %} Citi Hardware {% endblock %}

{% block css %}

<link href="{% static 'css/popup.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
{% if user.user_type == 'seller' %}
<div id="myModal" class="modal" data-ajax-url="{% url 'shop:create_item' %}">
    <div class="modal-content">
        <div style=" text-align: end;">
            <span class="close">&times;</span>
        </div>
        <div class="form">
            <h2>Add New Item</h2>
            <div style="text-align: left;">
                <form id="upload-Item" enctype="multipart/form-data">
                    {% csrf_token %}

                    <label for="itemName">Item Name</label>
                    <input type="text" name="itemName" id="itemName" style="width: 100%;">
                    <label for="description">Desription</label>
                    <input type="text" name="description" id="description" style="width: 100%;">
                    <label for="price">Price</label>
                    <input type="text" name="price" id="price" style="width: 100%;">
                    <label for="imgInp">Item Image</label>
                    <br>
                    <input type="file" src="" alt="" name="itemImage" accept="image/*" id="imgInp">
                    <br>

                    <img id="blah" src="#" alt="Image Preview" /
                        style="    width: -webkit-fill-available;height: auto;">
                    <br>
                    <button type="submit" class="btn btn-success">Upload</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="myModal1" class="modal" data-ajax-url="{% url 'shop:create_ads' %}" data-csrf-token="{{ csrf_token }}">
    <div class="modal-content">
        <div style=" text-align: end;">
            <span class="close">&times;</span>
        </div>
        <div class="form" id="form">
            <h2>Add New Ads Campaign</h2>

            <form id="upload-file" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="ads_name">Campaign Name</label>
                <input type="text" name="ads_name" id="ads_name" style="width: 100%;">
                <label for="ads_description">Desription</label>
                <input type="text" name="ads_description" id="ads_description" style="width: 100%;">
                <label for="ads_image">Ads Image</label>
                <br>
                <input type="file" name="file" id="imgInput">
                <br>
                <img id="preview1" src="#" alt="Image Preview" /
                    style="    width: -webkit-fill-available;height: auto;">
                <br>
                <button type="submit" class="btn btn-success">Upload</button>
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

{% block body %}
    <div id="main1" style="position: absolute; top: 6vh; width: 100%; display: flex; ">
        <!-- space for adds -->
        {% if user.user_type == 'shopper' %}
        <div
            style="width: 25%; height: 92vh; background-color: wheat; margin: auto; margin-top: 0px; position: sticky; top: 6vh;">
            dito ang Categories
        </div>
        {% endif %}
        <div style="width: 70%; overflow-x: hidden; margin: auto; overflow-y: scroll; height: 92vh;">
            <div style="height: 40vh ; background-color: chocolate; text-align: center; margin: auto;" id="adsDiv"
                data-ajax-url="{% url 'shop:ads' %}" data-ajax-User-id="{{ user.id }}">
                {% block ads %}
                {% endblock %}
            </div>
            <div style="height: auto; width: 100%; background-color: aquamarine;text-align: center;">

                <div class="slideshow-container" id="slideContainer" style="text-align: center;">
                    <h1 style="padding-top: 50px;">Shop Products</h1>
                </div>

                <div class="cardContainer" id="cardContainer" data-ajax-url="{% url 'shop:items' %}">


                </div>


            </div>
        </div>
    </div>


{% endblock %}
{% block js %}
<script src="{% static 'js/popup-home.js' %}"></script>
{% if user.user_type == 'seller' %}
<script src="{% static 'js/shop.js' %}"></script>
{% endif %}
<script src="{% static 'js/ads.js' %}"></script>
{% endblock %}